
state_file: ./state.json

devices:
  mpv1:
    enabled: false
    port: /dev/mpv1
    baud: 9600
    init:
      # port: state
      1: 3

  mpv2:
    enabled: false
    port: /dev/mpv1
    port: /dev/mpv2
    baud: 9600
    init:
      1: 3

  mpv3:
    enabled: false
    port: /dev/mpv3
    baud: 9600
    init:
      1: A

  sv:
    enabled: false
    port: /dev/relay
    baud: 115200
    mapping:
      1: 2
      2: 3
      3: 4
      4: 5
      5: 6
      6: 7
      7: 8
    init:
      1: 1
      2: 1
      3: 1
      4: 1
      5: 0
      6: 0
      7: 0
      8: 0

  gpio:
    enabled: true
    mapping:
      # relay: pin
      1: 2
      2: 3
    init:
      # port: state
      1: 0
      2: 1

sequence:
  - 0.1,gpio,1,on
  - 0.5,gpio,1,off

    #  - 0.1,sv,1,on
    #  - 0.5,sv,1,off
    #  - 20,sv,2,on
    #  - 20,sv,3,on
    #  - 20,mpv1,1,4
    #  - 20,sv4,on
    #  - 21,sv4,off
    #  - 21,mpv1,2
    #  - 21,sv2,off
    #  - 21,sv3,off
    #  - 21.1,sv1,on
    #  - 21.5,sv1,off
    #  - 20,sv2,on
    #  - 20,sv3,on
    #  - 20,mpv2,1
    #  - 20,sv6,on
    #  - 21,sv6,off
    #  - 21,mpv2,3
    #  - 21,sv2,off
    #  - 21,sv3,off
    #  - 21.1,sv1,on
    #  - 21.1,sv1,off
    #  - 61,mpv1,1
    #  - 61,sv5,on
    #  - 61,mpv3,B
    #  - 61,sv5,off
    #  - 81,mpv2,4
    #  - 81,sv7,on
    #  - 81,sv7,off
    #  - 101,mpv3,A
