#!/usr/bin/env python
import cgi
import cgitb
import os
import yaml
from subprocess import run, PIPE, check_output

cgitb.enable()

print("Content-Type: text/html")
print(
    """
<html>
	<header>
		<style>
table, th, td {
	border: 1px solid black;
}
		</style>
	</header>
	<body>
    <h1>Valve Controller</h1>"""
)

form = cgi.FieldStorage()

if form:
    fileitem = form["filename"]
    open("/root/config.yml.tmp", "wb").write(fileitem.file.read())
    try:
        yaml.safe_load(open("/root/config.yml.tmp"))
        print("<p>Config uploaded</p>")
        os.rename("/root/config.yml.tmp", "/root/config.yml")
        run(["/etc/init.d/valve-controller", "restart"])
    except Exception as e:
        print("<p>Config error</p>")
        print(f"<pre>{e}</pre>")

log = "\n".join(
    check_output("logread -e valve-controller", shell=True, text=True).splitlines()[-20:-1]
)

print(
    f"""
		Upload new configuration:
		<form enctype="multipart/form-data" action="/cgi-bin/valve-cgi" method="POST">
			<input type="file" name="filename">
			<input type="submit">
		</form>
		<table id="states"></table>
        <h3>Log</h3>
        No automatic reload
        <pre>{log}</pre>
		<script src="/valve-controller.js"> </script>
	</body>
</html>"""
)
