#!/usr/bin/env python
import cgi
import cgitb

cgitb.enable()

print("Content-Type: text/plain")
print()

form = cgi.FieldStorage()
fileitem = form["filename"]
open("/root/config.yml", "wb").write(fileitem.file.read())

print("Config uploaded")
