
manual_mode: false
states_file: /www/states.json
data_file: /www/data.csv
step_file: /tmp/valve-controller-step

devices:
  mpv1:
    enabled: false
    port: /dev/mpv1
    baud: 9600
    init:
      # port: state
      1: 2

  mpv2:
    enabled: false
    port: /dev/mpv2
    baud: 9600
    init:
      1: 1

  mpv3:
    enabled: false
    port: /dev/mpv3
    baud: 9600
    init:
      1: A

  sv:
    enabled: false
    port: /dev/relay
    baud: 115200
    mapping:
      1: 2
      2: 3
      3: 4
      4: 5
      5: 6
      6: 7
      7: 8
    init:
      # 1: 1 broken
      2: 0
      3: 0
      4: 0
      5: 0
      6: 0
      7: 0

  gpio:
    enabled: true
    mapping:
      # relay: pin
      # RaspberryPi 4 B setup
      1: 17
      2: 27
      3: 22
      4: 23
      5: 24
      6: 10
      7: 9
      8: 25
      9: 11
      10: 8
      11: 7
      12: 5
      13: 6
      14: 12
      15: 13
      16: 19
    init:
      # port: state
      1: 1
      2: 1
      3: 1

# set to `false` for single sequence run
sequence_loop: true

sequence:
  - 0.1,gpio,1,1
  - 0.1,gpio,2,1
  - 0.2,gpio,1,0
  - 0.3,gpio,1,1
  - 0.4,gpio,2,0
  - 0.4,gpio,1,0

sequence_test:
  # Reboot program (this discharges any water sample in the system)
  - 0.1,sv,2,1
  - 0.15,sv,3,1
  - 0.2,mpv1,1,4
  - 1.2,sv,2,0
  - 1.25,sv,3,0
  - 1.3,mpv1,1,3
  - 1.35,sv,5,1
  - 2.0,sv,5,0
