#!/bin/sh /etc/rc.common

USE_PROCD=1
START=95
STOP=01

extra_command "init" "Reset valves to init state"

start_service() {
	procd_open_instance valve-controller
	procd_set_param command python -u /usr/bin/valve-controller
	procd_append_param command /root/config.yml
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

init() {
	rm -rf /tmp/valve-controller-step
	/usr/bin/valve-controller /root/config.yml init > /dev/null
}
